### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by NobodyXu** [RookAndPawn/ev_slotmap#2]
^

**Comment by johnhurt** [comment]
Technically yes. I don’t think anyone but me is using it 😊

**Comment by NobodyXu** [comment]
Thanks for replying.

I wanted to use this crate for it has concurrent read/write support, however I found that the `Index` it returned is too large for my project, so I ended up not using it.

**Comment by johnhurt** [comment]
Yeah, size is a drawback to this trick this library uses to be multithreaded. You basically store two copies of everything. The shallow copy trait can alleviate that a little.

**Comment by NobodyXu** [comment]
> Yeah, size is a drawback to this trick this library uses to be multithreaded. You basically store two copies of everything. The shallow copy trait can alleviate that a little.

I read about this in [`left-right`](https://github.com/jonhoo/left-right).

It does waste a bit of space, however it is a clever technique to add almost wait-free concurrent read support to any container you like.

> size is a drawback to this trick

I am actually talking about the size of the key.

This crate returns a key that is a least 64-bit since it stores a pointer, however I need one `slotmap` that returns a `u32`.

At last, I chose [LPGhatguy/thunderdome](https://github.com/LPGhatguy/thunderdome) for its `Index` contains a `u32` slot which can be used to uniquely identify a problem.

Only downside to this solution is that I have to use a `parking_lot::RwLock` and that might blocks the reader.
This might be a problem since in my project, there can be many threads will add and remove a slot, while there is another thread that constantly read the slot and modifies it by using a `Mutex` for each slot.

However since my project has just started and there isn't any benchmark or complaint, I will probably sticks with the current solution.

**Comment by NobodyXu** [comment]
Well, after I second thought, I realized the solution offered by left-right might not be beneficial to me since I have mutiple writers…

**Comment by johnhurt** [comment]
Ah, yeah. The size of the key is based on what I am using in the underlying [oneway-slotmap](https://github.com/RookAndPawn/one_way_slot_map). I would be open to adding a way to making the key a u32 instead of a u64. If you think that would be useful, just open up an issue on that repo.

This project and Left-Right are effectively the same thing, they're both derived form [evmap](https://github.com/jonhoo/evmap), so both of them have single-thread access to the writer. Based on what you said, I think you're better off a rwlock around one of the other slotmaps. If you want my 2 cents, I the tokio rwlock is a little better than the parking lot one because it will help prevent the writer from being starved.

**Comment by NobodyXu** [comment]
Yeah.

I am currently using parking_lot::RwLock<thunderdome::Arena>, however I am thinking of writing my own concurrent write SlotMap, since RwLock can only have one writer at a time and it blocks the reader.
